[package]
description = "HTTP client IP address extractors"
edition = "2024"
license = "MIT"
name = "client-ip"
repository = "https://github.com/imbolc/client-ip"
version = "0.1.0"

[features]
default = []
forwarded-header = ["dep:forwarded-header-value"]

[dependencies]
forwarded-header-value = { version = "0.1", optional = true }
http = "1"

[lints.rust]
unsafe_code = "forbid"
future_incompatible = { level = "deny", priority = -2 }
keyword_idents = { level = "deny", priority = -2 }
let_underscore = { level = "deny", priority = -2 }
missing_docs = "deny"
nonstandard_style = { level = "deny", priority = -2 }
refining_impl_trait = { level = "deny", priority = -2 }
rust_2018_compatibility = { level = "deny", priority = -2 }
rust_2018_idioms = { level = "deny", priority = -2 }
rust_2021_compatibility = { level = "deny", priority = -2 }
rust_2024_compatibility = { level = "deny", priority = -2 }
unreachable_pub = { level = "warn", priority = -1 }
unused = { level = "warn", priority = -1 }

[lints.clippy]
all = { level = "warn", priority = -1 }
